const Log = require("./index");

const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJwZTQxMTFAc3JtaXN0LmVkdS5pbiIsImV4cCI6MTc3NzcwMTY1OCwiaWF0IjoxNzc3NzAwNzU4LCJpc3MiOiJBZmZvcmQgTWVkaWNhbCBUZWNobm9sb2dpZXMgUHJpdmF0ZSBMaW1pdGVkIiwianRpIjoiYTQ5ZTZhYTQtNjMxNS00ZjhjLTlkNDQtODhkNjM2YTc3YWEzIiwibG9jYWxlIjoiZW4tSU4iLCJuYW1lIjoicG9vamEgZWxsYW50aSIsInN1YiI6IjkyMzVlY2JkLTEyNmMtNDlmZS1iODIyLTVmMTU1OGJiNDkwZSJ9LCJlbWFpbCI6InBlNDExMUBzcm1pc3QuZWR1LmluIiwibmFtZSI6InBvb2phIGVsbGFudGkiLCJyb2xsTm8iOiJyYTIzMTEwMDMwMTAxNDciLCJhY2Nlc3NDb2RlIjoiUWticHhIIiwiY2xpZW50SUQiOiI5MjM1ZWNiZC0xMjZjLTQ5ZmUtYjgyMi01ZjE1NThiYjQ5MGUiLCJjbGllbnRTZWNyZXQiOiJzUlVyd3JVZW5YVnB0Tk5KIn0.ocxXiLWGxogI5QHHkuD1i0bYqps9O15ubXNhmju8DFs";

Log(
  "frontend",
  "info",
  "api",
  "Middleware working",
  token
).then(console.log);


